# # blacklist
# branches:
#   except:
#     - legacy
#     - experimental
#     - stagging

language: cpp
dist: focal
compiler: gcc
os: linux
sudo: true
env:
  - BUILD_TYPE=Debug

# whitelist
branches:
  only:
    - master
    - /v\d+\.\d+[a-z]/

# default gcc for Ubuntu Focal is v9, upgraded to v10 here
# It increases build time by ~1 min
addons:
  apt:
    sources:
      - sourceline: “ppa:ubuntu-toolchain-r/test”
    packages:
      - gcc-10
      - g++-10
      - libglew-dev
      - libglfw3-dev
      - libglm-dev
      - libstb-dev

script:
# /usr/bin/gcc points to an older compiler on Linux.
  - export CC=gcc-10
  - export CXX=g++-10
  - cmake --version
  - mkdir build
  - cd build 
  - cmake ../CMakeLists.txt
  - cmake --build .. --target all

before_deploy:
  - echo "Deploying build"
  - tar -zcf ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz ./build ./annex

deploy:
# GitHub -Add zip to release
- provider: releases
  api_key:
    secure: "ILAAI+S2mhuFmMt2fA1CutS98IWWH3JuZvMkOY509/k9CTATPAmnefPz7p2CXi7/ZzYoWohwfFBBqxr3LhKISxVbIyKHjzGrfXV0bmdeOgIOEujfNn51K9qpR3cOFzTaewG6FbB30Z7kInPdA0LYaU9pkR0DWEWwMoxj6NIDjaA3RcpC09FwV/KnLL6Tl62/xjlBa55PDoyhZAnZ1GHTKsJ1//7dszxOWGkpcoV5tFr0/fdrbb2oRb2n2q04CK5vJ11AegcXP8Os5IxDz6hl+FRTkXZv5mkrywwgpEyuIuIRhHMMM7KFkGQCn6feswSyDWDX81hP3ahLKTYyZ6ZDgeXn8k/kKBJlQN4LvvHj6Peo69G3UaQz6ELRJ4dQKXVe6YcaqWtrHLZBmmWYUNyt5eYi2CT/wFX5PMxNr6uaCQ5KuZK2HLMaDv1tF7ug2Ub2D0IftdGVrnWrhseH9CnlWi8n1G2EPIeNMt00DgFJeAhLtAyfBmCIFP31b1I6eTR605SXkpS0yKEkjN3Q5NQdG1MU1FLGNOfHDnNV2vFY8fX6aIPK0sFW+U4D/5xUBxX13hfk3/KZka7ZRhbbSHgDxoHBzM9ih6/ZlRMrBEMGhF0QSWb3iTfH0Rd1+1Q4qh9yrFtf1VLO+yfGAVDyrABA+5NIJNL4zFqEBN3LcJGssHI="
  file_glob: true
  file: ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
  skip_cleanup: true
  on:
    tags: true
