language: cpp
dist: focal
compiler: gcc
sudo: true

# whitelist
branches:
  only:
    - /^v\d+(\.\d+)+$/
    - master

# default gcc for Ubuntu Focal is v9, upgraded to v10 here
# It increases build time by ~1min
addons:
  apt:
    sources:
      - sourceline: “ppa:ubuntu-toolchain-r/test”
    packages:
      - gcc-10
      - g++-10
      - libglew-dev
      - libglfw3-dev
      - libglm-dev
      - libstb-dev
      - jshon # needed for "body"

matrix:
  - os: linux
    env: BUILD_TYPE=Debug

  - os: linux
    env: BUILD_TYPE=Release


script:
# /usr/bin/gcc points to an older compiler on Linux.
  - export CC=gcc-10
  - export CXX=g++-10
  - cmake --version
  - mkdir build
  - cd build 
  - cmake ..
  - make

before_deploy:
  - echo "Preparing to deploy build"
  - export BODY=$(jshon -s "$(cat CHANGELOG.md)")
  - echo $BODY
  - cd ..
  - tar -zcf ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_TYPE}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz ./build ./inc ./annex ./LICENSE.md

deploy:
# GitHub - Add zip to release
- provider: releases
  api_key:
    secure: "ILAAI+S2mhuFmMt2fA1CutS98IWWH3JuZvMkOY509/k9CTATPAmnefPz7p2CXi7/ZzYoWohwfFBBqxr3LhKISxVbIyKHjzGrfXV0bmdeOgIOEujfNn51K9qpR3cOFzTaewG6FbB30Z7kInPdA0LYaU9pkR0DWEWwMoxj6NIDjaA3RcpC09FwV/KnLL6Tl62/xjlBa55PDoyhZAnZ1GHTKsJ1//7dszxOWGkpcoV5tFr0/fdrbb2oRb2n2q04CK5vJ11AegcXP8Os5IxDz6hl+FRTkXZv5mkrywwgpEyuIuIRhHMMM7KFkGQCn6feswSyDWDX81hP3ahLKTYyZ6ZDgeXn8k/kKBJlQN4LvvHj6Peo69G3UaQz6ELRJ4dQKXVe6YcaqWtrHLZBmmWYUNyt5eYi2CT/wFX5PMxNr6uaCQ5KuZK2HLMaDv1tF7ug2Ub2D0IftdGVrnWrhseH9CnlWi8n1G2EPIeNMt00DgFJeAhLtAyfBmCIFP31b1I6eTR605SXkpS0yKEkjN3Q5NQdG1MU1FLGNOfHDnNV2vFY8fX6aIPK0sFW+U4D/5xUBxX13hfk3/KZka7ZRhbbSHgDxoHBzM9ih6/ZlRMrBEMGhF0QSWb3iTfH0Rd1+1Q4qh9yrFtf1VLO+yfGAVDyrABA+5NIJNL4zFqEBN3LcJGssHI="
  file_glob: true
  file: ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_TYPE}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
  skip_cleanup: true
  on:
    tags: true
  body: ${BODY}